#install.packages("data.table")
library(data.table)
#install.packages("stringr")
library(stringr)
#install.packages("sqldf")
library(sqldf)
#install.packages("knitr")
library(knitr)
#install.packages("anytime")
library(anytime)
#install.packages("knitr")
library(knitr)
#install.packages('dplyr')
library(dplyr)
#install.packages('dtplyr')
library(dtplyr)

Tennis_hist<-fread(file='../Data/atp_matches.csv', header = T)
#On garde uniquement les lignes où on dispose des informations détaillées de match
Tennis_table=Tennis_hist[!is.na(minutes)&substr(tourney_name,0,9)!='Davis Cup']
atp_players<- fread(file ='../Data/atp_players.csv' ,header = F)
colnames(atp_players)=c("Player_Id","Prenom","Nom","Main_Forte","DateNaissance","Nationalite")
Rank<- fread(file ='../Data/rankings.csv' , header = F)
colnames(Rank)<-c("DateRanking","Numero","Player_Id","Points")